sonar.issue.ignore.multicriteria=tailwindThemeNewWebV2,tailwindThemeNewWeb,tailwindThemeWeb

sonar.issue.ignore.multicriteria.tailwindThemeNewWebV2.ruleKey=css:S4662
sonar.issue.ignore.multicriteria.tailwindThemeNewWebV2.resourceKey=frontend/new-web-v2/src/styles/index.css

sonar.issue.ignore.multicriteria.tailwindThemeNewWeb.ruleKey=css:S4662
sonar.issue.ignore.multicriteria.tailwindThemeNewWeb.resourceKey=frontend/new-web/src/index.css

sonar.issue.ignore.multicriteria.tailwindThemeWeb.ruleKey=css:S4662
sonar.issue.ignore.multicriteria.tailwindThemeWeb.resourceKey=frontend/web/src/index.css
