#include "AgentConfiguration.h"
#include <fstream>
#include <nlohmann/json.hpp>
#include <sstream>

namespace codepilot {

using json = nlohmann::json;

AgentConfiguration &AgentConfiguration::getInstance() {
  static AgentConfiguration instance;
  return instance;
}

bool AgentConfiguration::init(const std::string &configPath) {
  configPath_ = configPath;
  return reconfigure();
}

bool AgentConfiguration::reconfigure() {
  std::lock_guard<std::mutex> lock(mutex_);

  std::ifstream file(configPath_);
  if (!file.is_open())
    return false;

  std::stringstream buf;
  buf << file.rdbuf();
  rawJson_ = buf.str();

  try {
    json j = json::parse(rawJson_);
    experts_.clear();

    if (j.contains("experts") && j["experts"].is_array()) {
      for (const auto &e : j["experts"]) {
        experts_.push_back(ExpertConfig::fromJson(e));
      }
    } else if (j.is_array()) {
      for (const auto &e : j) {
        experts_.push_back(ExpertConfig::fromJson(e));
      }
    }

    // 如果 JSON 有顶层 llm_provider 等字段，注入到每个 Expert（全局默认降级）
    std::string globalProvider = j.value("llm_provider", "");
    std::string globalModel = j.value("llm_model", "");
    int globalTimeout = j.value("llm_timeout", 0);
    double globalTemperature = j.value("llm_temperature", -1.0);

    for (auto &expert : experts_) {
      if (expert.llmProvider.empty() && !globalProvider.empty())
        expert.llmProvider = globalProvider;
      if (expert.llmModel.empty() && !globalModel.empty())
        expert.llmModel = globalModel;
      if (expert.llmTimeout == 0 && globalTimeout > 0)
        expert.llmTimeout = globalTimeout;
      if (expert.llmTemperature < 0 && globalTemperature >= 0)
        expert.llmTemperature = globalTemperature;
    }

    return !experts_.empty();
  } catch (const std::exception &) {
    return false;
  }
}

std::string AgentConfiguration::exportJson() const {
  std::lock_guard<std::mutex> lock(mutex_);

  json j;
  j["_comment"] = "CodePilot Expert Configuration - generated by "
                  "AgentConfiguration::exportJson()";
  j["_config_path"] = configPath_;

  json expertsArray = json::array();
  for (const auto &e : experts_) {
    json ej;
    ej["name"] = e.name;
    ej["description"] = e.description;
    ej["prompt_template"] = e.promptTemplate;
    ej["is_entry"] = e.isEntry;
    ej["context_isolation"] = e.contextIsolation;
    ej["context_template"] = e.contextTemplate;

    // 应用层
    if (!e.visibleTools.empty()) {
      ej["visible_tools"] = e.visibleTools;
    }

    // 系统层
    if (!e.canModifyPlan)
      ej["can_modify_plan"] = false;
    if (e.canWriteSummary)
      ej["can_write_summary"] = true;
    if (e.readGlobalActively)
      ej["read_global_actively"] = true;
    if (e.maxGlobalRounds > 0)
      ej["max_global_rounds"] = e.maxGlobalRounds;

    // LLM
    if (!e.llmProvider.empty())
      ej["_llm_provider"] = e.llmProvider;
    if (!e.llmModel.empty())
      ej["_llm_model"] = e.llmModel;
    if (e.llmTimeout > 0)
      ej["_llm_timeout"] = e.llmTimeout;
    if (e.llmTemperature >= 0)
      ej["_llm_temperature"] = e.llmTemperature;

    // 路由
    json rules = json::array();
    for (const auto &r : e.nextRules) {
      json rj;
      switch (r.conditionType) {
      case RouteRule::TagExists:
        rj["type"] = "tag_exists";
        break;
      case RouteRule::TagValueMatch:
        rj["type"] = "tag_value_match";
        break;
      case RouteRule::PlanState:
        rj["type"] = "plan_state";
        break;
      default:
        rj["type"] = "default";
        break;
      }
      rj["value"] = r.conditionValue;
      rj["route_to"] = r.routeTo;
      rj["priority"] = r.priority;
      rules.push_back(rj);
    }
    if (!rules.empty())
      ej["next_rules"] = rules;
    if (!e.onFailRoute.empty())
      ej["on_fail"] = e.onFailRoute;

    // 容量
    ej["max_internal_rounds"] = e.maxInternalRounds;
    ej["tool_timeout_seconds"] = e.toolTimeoutSeconds;

    expertsArray.push_back(ej);
  }
  j["experts"] = expertsArray;

  return j.dump(2);
}

bool AgentConfiguration::importJson(const std::string &jsonStr) {
  std::lock_guard<std::mutex> lock(mutex_);

  try {
    json j = json::parse(jsonStr);
    experts_.clear();

    if (j.contains("experts") && j["experts"].is_array()) {
      for (const auto &e : j["experts"]) {
        experts_.push_back(ExpertConfig::fromJson(e));
      }
    } else if (j.is_array()) {
      for (const auto &e : j) {
        experts_.push_back(ExpertConfig::fromJson(e));
      }
    } else {
      return false;
    }

    rawJson_ = jsonStr;
    return !experts_.empty();
  } catch (const std::exception &) {
    return false;
  }
}

bool AgentConfiguration::saveToFile() const { return saveToFile(configPath_); }

bool AgentConfiguration::saveToFile(const std::string &targetPath) const {
  std::lock_guard<std::mutex> lock(mutex_);

  std::string content = exportJson();
  std::ofstream file(targetPath);
  if (!file.is_open())
    return false;

  file << content;
  file.close();
  return true;
}

const ExpertConfig *
AgentConfiguration::getExpert(const std::string &name) const {
  std::lock_guard<std::mutex> lock(mutex_);
  for (const auto &e : experts_) {
    if (e.name == name)
      return &e;
  }
  return nullptr;
}

const ExpertConfig *AgentConfiguration::getEntryExpert() const {
  std::lock_guard<std::mutex> lock(mutex_);
  for (const auto &e : experts_) {
    if (e.isEntry)
      return &e;
  }
  return experts_.empty() ? nullptr : &experts_.front();
}

std::vector<std::string> AgentConfiguration::listExpertNames() const {
  std::lock_guard<std::mutex> lock(mutex_);
  std::vector<std::string> names;
  for (const auto &e : experts_) {
    names.push_back(e.name);
  }
  return names;
}

std::vector<ExpertConfig> AgentConfiguration::allExperts() const {
  std::lock_guard<std::mutex> lock(mutex_);
  return experts_;
}

bool AgentConfiguration::isReady() const {
  std::lock_guard<std::mutex> lock(mutex_);
  return !experts_.empty();
}

std::string AgentConfiguration::rawJson() const {
  std::lock_guard<std::mutex> lock(mutex_);
  return rawJson_;
}

// ============================================================
// Expert CRUD
// ============================================================

bool AgentConfiguration::addExpert(const ExpertConfig &expert) {
  std::lock_guard<std::mutex> lock(mutex_);
  // 检查名称冲突
  for (const auto &e : experts_) {
    if (e.name == expert.name)
      return false;
  }
  experts_.push_back(expert);
  rebuildRawJson();
  return true;
}

bool AgentConfiguration::updateExpert(const std::string &name,
                                      const ExpertConfig &config) {
  std::lock_guard<std::mutex> lock(mutex_);
  for (auto &e : experts_) {
    if (e.name == name) {
      e = config;
      e.name = name; // 保持名称不变
      rebuildRawJson();
      return true;
    }
  }
  return false;
}

bool AgentConfiguration::patchExpert(const std::string &name,
                                     const std::string &jsonPatch) {
  std::lock_guard<std::mutex> lock(mutex_);
  try {
    json patch = json::parse(jsonPatch);
    if (!patch.is_object())
      return false;

    for (auto &e : experts_) {
      if (e.name != name)
        continue;

      // ---- 基本字段 ----
      if (patch.contains("description"))
        e.description = patch["description"].get<std::string>();
      if (patch.contains("prompt_template"))
        e.promptTemplate = patch["prompt_template"].get<std::string>();
      if (patch.contains("is_entry"))
        e.isEntry = patch["is_entry"].get<bool>();
      if (patch.contains("context_isolation"))
        e.contextIsolation = patch["context_isolation"].get<bool>();
      if (patch.contains("context_template"))
        e.contextTemplate = patch["context_template"].get<std::string>();

      // ---- 应用层 ----
      if (patch.contains("visible_tools") &&
          patch["visible_tools"].is_array()) {
        e.visibleTools.clear();
        for (const auto &t : patch["visible_tools"])
          e.visibleTools.push_back(t.get<std::string>());
      }

      // ---- 系统层 ----
      if (patch.contains("can_modify_plan"))
        e.canModifyPlan = patch["can_modify_plan"].get<bool>();
      if (patch.contains("can_write_summary"))
        e.canWriteSummary = patch["can_write_summary"].get<bool>();
      if (patch.contains("read_global_actively"))
        e.readGlobalActively = patch["read_global_actively"].get<bool>();
      if (patch.contains("max_global_rounds"))
        e.maxGlobalRounds = patch["max_global_rounds"].get<int>();

      // ---- LLM ----
      if (patch.contains("llm_provider"))
        e.llmProvider = patch["llm_provider"].get<std::string>();
      if (patch.contains("llm_model"))
        e.llmModel = patch["llm_model"].get<std::string>();
      if (patch.contains("llm_timeout"))
        e.llmTimeout = patch["llm_timeout"].get<int>();
      if (patch.contains("llm_temperature"))
        e.llmTemperature = patch["llm_temperature"].get<double>();

      // ---- 路由 ----
      if (patch.contains("next_rules") && patch["next_rules"].is_array()) {
        e.nextRules.clear();
        for (const auto &r : patch["next_rules"])
          e.nextRules.push_back(RouteRule::fromJson(r));
      }
      if (patch.contains("on_fail"))
        e.onFailRoute = patch["on_fail"].get<std::string>();

      // ---- 容量 ----
      if (patch.contains("max_internal_rounds"))
        e.maxInternalRounds = patch["max_internal_rounds"].get<int>();
      if (patch.contains("tool_timeout_seconds"))
        e.toolTimeoutSeconds = patch["tool_timeout_seconds"].get<int>();

      rebuildRawJson();
      return true;
    }
    return false;
  } catch (const std::exception &) {
    return false;
  }
}

bool AgentConfiguration::removeExpert(const std::string &name) {
  std::lock_guard<std::mutex> lock(mutex_);
  auto it =
      std::find_if(experts_.begin(), experts_.end(),
                   [&name](const ExpertConfig &e) { return e.name == name; });
  if (it == experts_.end())
    return false;
  experts_.erase(it);
  rebuildRawJson();
  return true;
}

// ============================================================
// Expert 子字段更新
// ============================================================

bool AgentConfiguration::setExpertTools(const std::string &name,
                                        const std::vector<std::string> &tools) {
  std::lock_guard<std::mutex> lock(mutex_);
  for (auto &e : experts_) {
    if (e.name == name) {
      e.visibleTools = tools;
      rebuildRawJson();
      return true;
    }
  }
  return false;
}

bool AgentConfiguration::setExpertRoutes(const std::string &name,
                                         const std::vector<RouteRule> &routes) {
  std::lock_guard<std::mutex> lock(mutex_);
  for (auto &e : experts_) {
    if (e.name == name) {
      e.nextRules = routes;
      rebuildRawJson();
      return true;
    }
  }
  return false;
}

bool AgentConfiguration::addExpertRoute(const std::string &name,
                                        const RouteRule &rule) {
  std::lock_guard<std::mutex> lock(mutex_);
  for (auto &e : experts_) {
    if (e.name == name) {
      e.nextRules.push_back(rule);
      rebuildRawJson();
      return true;
    }
  }
  return false;
}

bool AgentConfiguration::removeExpertRoute(const std::string &name, int index) {
  std::lock_guard<std::mutex> lock(mutex_);
  for (auto &e : experts_) {
    if (e.name == name) {
      if (index < 0 || static_cast<size_t>(index) >= e.nextRules.size())
        return false;
      e.nextRules.erase(e.nextRules.begin() + index);
      rebuildRawJson();
      return true;
    }
  }
  return false;
}

bool AgentConfiguration::setExpertLlm(const std::string &name,
                                      const std::string &provider,
                                      const std::string &model, int timeout,
                                      double temperature) {
  std::lock_guard<std::mutex> lock(mutex_);
  for (auto &e : experts_) {
    if (e.name == name) {
      e.llmProvider = provider;
      e.llmModel = model;
      e.llmTimeout = timeout;
      e.llmTemperature = temperature;
      rebuildRawJson();
      return true;
    }
  }
  return false;
}

// ============================================================
// 全局 LLM 默认值
// ============================================================

AgentConfiguration::GlobalLlmDefaults
AgentConfiguration::getGlobalLlmDefaults() const {
  std::lock_guard<std::mutex> lock(mutex_);
  GlobalLlmDefaults g;
  // 从 rawJson_ 解析顶层字段（不对应任何 Expert）
  try {
    json j = json::parse(rawJson_);
    g.provider = j.value("llm_provider", "");
    g.model = j.value("llm_model", "");
    g.timeout = j.value("llm_timeout", 0);
    g.temperature = j.value("llm_temperature", -1.0);
  } catch (...) {
  }
  return g;
}

bool AgentConfiguration::setGlobalLlmDefaults(
    const GlobalLlmDefaults &defaults) {
  std::lock_guard<std::mutex> lock(mutex_);
  try {
    json j = json::parse(rawJson_);
    if (!defaults.provider.empty())
      j["llm_provider"] = defaults.provider;
    if (!defaults.model.empty())
      j["llm_model"] = defaults.model;
    if (defaults.timeout > 0)
      j["llm_timeout"] = defaults.timeout;
    if (defaults.temperature >= 0)
      j["llm_temperature"] = defaults.temperature;
    rawJson_ = j.dump(2);
    return true;
  } catch (...) {
    return false;
  }
}

// ============================================================
// 配置验证
// ============================================================

bool AgentConfiguration::validate(const std::string &jsonStr,
                                  std::string &errorOut) {
  try {
    json j = json::parse(jsonStr);
    if (!j.contains("experts") || !j["experts"].is_array()) {
      errorOut = "缺少 experts 数组";
      return false;
    }
    for (size_t i = 0; i < j["experts"].size(); ++i) {
      const auto &e = j["experts"][i];
      if (!e.contains("name") || !e["name"].is_string()) {
        errorOut = "experts[" + std::to_string(i) + "] 缺少 name 字段";
        return false;
      }
      if (e.contains("next_rules") && e["next_rules"].is_array()) {
        for (size_t ri = 0; ri < e["next_rules"].size(); ++ri) {
          const auto &r = e["next_rules"][ri];
          if (!r.contains("route_to") || !r["route_to"].is_string()) {
            errorOut = "experts[" + std::to_string(i) + "].next_rules[" +
                       std::to_string(ri) + "] 缺少 route_to";
            return false;
          }
        }
      }
    }
    return true;
  } catch (const std::exception &ex) {
    errorOut = std::string("JSON 解析失败: ") + ex.what();
    return false;
  }
}

std::string AgentConfiguration::configPath() const {
  std::lock_guard<std::mutex> lock(mutex_);
  return configPath_;
}

// ============================================================
// 内部辅助
// ============================================================

void AgentConfiguration::rebuildRawJson() {
  // 从当前 experts_ 重建 rawJson_
  try {
    json j = json::parse(rawJson_); // 保留顶层注释/元数据
    json arr = json::array();
    for (const auto &e : experts_) {
      json ej;
      ej["name"] = e.name;
      ej["description"] = e.description;
      if (!e.promptTemplate.empty())
        ej["prompt_template"] = e.promptTemplate;
      ej["is_entry"] = e.isEntry;
      ej["context_isolation"] = e.contextIsolation;
      ej["context_template"] = e.contextTemplate;

      if (!e.visibleTools.empty())
        ej["visible_tools"] = e.visibleTools;

      ej["can_modify_plan"] = e.canModifyPlan;
      if (e.canWriteSummary)
        ej["can_write_summary"] = true;
      if (e.readGlobalActively)
        ej["read_global_actively"] = true;
      if (e.maxGlobalRounds > 0)
        ej["max_global_rounds"] = e.maxGlobalRounds;

      if (!e.llmProvider.empty())
        ej["_llm_provider"] = e.llmProvider;
      if (!e.llmModel.empty())
        ej["_llm_model"] = e.llmModel;
      if (e.llmTimeout > 0)
        ej["_llm_timeout"] = e.llmTimeout;
      if (e.llmTemperature >= 0)
        ej["_llm_temperature"] = e.llmTemperature;

      json rules = json::array();
      for (const auto &r : e.nextRules) {
        json rj;
        switch (r.conditionType) {
        case RouteRule::TagExists:
          rj["type"] = "tag_exists";
          break;
        case RouteRule::TagValueMatch:
          rj["type"] = "tag_value_match";
          break;
        case RouteRule::PlanState:
          rj["type"] = "plan_state";
          break;
        default:
          rj["type"] = "default";
          break;
        }
        rj["value"] = r.conditionValue;
        rj["route_to"] = r.routeTo;
        rj["priority"] = r.priority;
        rules.push_back(rj);
      }
      if (!rules.empty())
        ej["next_rules"] = rules;
      if (!e.onFailRoute.empty())
        ej["on_fail"] = e.onFailRoute;

      ej["max_internal_rounds"] = e.maxInternalRounds;
      ej["tool_timeout_seconds"] = e.toolTimeoutSeconds;

      arr.push_back(ej);
    }
    j["experts"] = arr;
    rawJson_ = j.dump(2);
  } catch (...) {
    // 重建失败，保留旧的 rawJson_
  }
}

} // namespace codepilot
